// <auto-generated />
using System;
using ConnectplusBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223152133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConnectplusBackend.Models.Agent", b =>
                {
                    b.Property<int>("AgentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentID"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Agent");

                    b.HasKey("AgentID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentID = 1,
                            CreatedAt = new DateTime(2026, 2, 23, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(99),
                            Department = "Support",
                            Email = "alice@connectplus.com",
                            FullName = "Alice Johnson",
                            IsActive = true,
                            Role = "Agent"
                        },
                        new
                        {
                            AgentID = 2,
                            CreatedAt = new DateTime(2026, 2, 23, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(102),
                            Department = "Support",
                            Email = "bob@connectplus.com",
                            FullName = "Bob Smith",
                            IsActive = true,
                            Role = "Agent"
                        },
                        new
                        {
                            AgentID = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(103),
                            Department = "Support",
                            Email = "carol@connectplus.com",
                            FullName = "Carol White",
                            IsActive = true,
                            Role = "Supervisor"
                        });
                });

            modelBuilder.Entity("ConnectplusBackend.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Address = "Hyderabad",
                            CreatedAt = new DateTime(2026, 2, 23, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(115),
                            Email = "john@email.com",
                            FullName = "John Doe",
                            IsActive = true,
                            Phone = "9000000001"
                        },
                        new
                        {
                            CustomerID = 2,
                            Address = "Bangalore",
                            CreatedAt = new DateTime(2026, 2, 23, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(117),
                            Email = "jane@email.com",
                            FullName = "Jane Roe",
                            IsActive = true,
                            Phone = "9000000002"
                        },
                        new
                        {
                            CustomerID = 3,
                            Address = "Mumbai",
                            CreatedAt = new DateTime(2026, 2, 23, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(118),
                            Email = "raj@email.com",
                            FullName = "Raj Kumar",
                            IsActive = true,
                            Phone = "9000000003"
                        });
                });

            modelBuilder.Entity("ConnectplusBackend.Models.Ticket", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketID"));

                    b.Property<int?>("AgentID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketID");

                    b.HasIndex("AgentID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CustomerID");

                    b.HasIndex("Status");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketID = 1,
                            AgentID = 1,
                            CategoryID = 1,
                            CreatedAt = new DateTime(2026, 2, 21, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(131),
                            CustomerID = 1,
                            Description = "Laptop shows black screen on boot.",
                            Priority = 2,
                            Status = 0,
                            Subject = "Laptop not starting"
                        },
                        new
                        {
                            TicketID = 2,
                            AgentID = 2,
                            CategoryID = 2,
                            CreatedAt = new DateTime(2026, 2, 22, 15, 21, 33, 346, DateTimeKind.Utc).AddTicks(137),
                            CustomerID = 2,
                            Description = "Charged extra for last month.",
                            Priority = 1,
                            Status = 1,
                            Subject = "Invoice mismatch"
                        },
                        new
                        {
                            TicketID = 3,
                            CategoryID = 3,
                            CreatedAt = new DateTime(2026, 2, 23, 10, 21, 33, 346, DateTimeKind.Utc).AddTicks(138),
                            CustomerID = 3,
                            Description = "Want to know about premium plan.",
                            Priority = 0,
                            Status = 0,
                            Subject = "Service inquiry"
                        });
                });

            modelBuilder.Entity("ConnectplusBackend.Models.TicketCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CategoryID");

                    b.ToTable("TicketCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Technical Support",
                            Description = "Hardware, software, network issues",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Billing",
                            Description = "Invoice, payment, subscription queries",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "General Enquiry",
                            Description = "General questions and information",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Complaint",
                            Description = "Customer complaints and escalations",
                            IsActive = true
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Service Request",
                            Description = "New service setup or changes",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("ConnectplusBackend.Models.Ticket", b =>
                {
                    b.HasOne("ConnectplusBackend.Models.Agent", "Agent")
                        .WithMany("Tickets")
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConnectplusBackend.Models.TicketCategory", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ConnectplusBackend.Models.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Category");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ConnectplusBackend.Models.Agent", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ConnectplusBackend.Models.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("ConnectplusBackend.Models.TicketCategory", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
